STAT3401Workbook.pdf : week1eda.tex week2matrix.tex week3Distance.tex week4cluster.tex week5pca.tex cancor.tex  week7hotelling.tex week8manova.tex week9pco.tex week10da.tex week11fa.tex STAT3401Workbook.tex
	pdflatex STAT3401Workbook
	pdflatex STAT3401Workbook
week1eda.tex : week1eda.Rnw
	R CMD BATCH .w1.R --silent
week2matrix.tex : week2matrix.Rnw
	R CMD BATCH .w2.R
week3Distance.tex : week3Distance.Rnw
	R CMD BATCH .w3.R
week4cluster.tex : week4cluster.Rnw
	R CMD BATCH .w4.R
week5pca.tex : week5pca.Rnw
	R CMD BATCH .w5.R
week7hotelling.tex : week7hotelling.Rnw
	R CMD BATCH .w7.R
week8manova.tex : week8manova.Rnw
	R CMD BATCH .w8.R
week9pco.tex : week9pco.Rnw
	R CMD BATCH .w9.R
week10da.tex : week10da.Rnw
	R CMD BATCH .w10.R
week11fa.tex : week11fa.Rnw
	R CMD BATCH .w11.R
